name: Apply IaC via Terraform & Ansible

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9
      - name: Add Terraform Backend for S3
        run: |
          cat << EOF > devops/tf/backend
          skip_credentials_validation = true
          skip_region_validation = true
          bucket="${{ secrets.LINODE_OBJECT_STORAGE_BUCKET }}"
          key="tryiac-ansible.tfstate"
          region="${{ secrets.LINODE_REGION }}"
          endpoint="${{ secrets.LINODE_REGION }}.linodeobjects.com"
          access_key="${{ secrets.LINODE_OBJECT_STORAGE_ACCESS_KEY }}"
          secret_key="${{ secrets.LINODE_OBJECT_STORAGE_SECRET_KEY }}"
          EOF
      - name: Add Terraform TFVars
        run: |
          cat << EOF > devops/tf/terraform.tfvars
          linode_pa_token="${{ secrets.LINODE_ACCESS_TOKEN }}"
          authorized_key="${{ secrets.SSH_PUB_KEY }}"
          root_user_pw="${{ secrets.ROOT_USER_PW }}"
          linode_instance_count="${{ secrets.WEBAPPS_COUNT }}"
          EOF
      - name: Terraform Init
        run: terraform -chdir=./devops/tf init -backend-config=backend
      - name: Terraform Validate 
        run: terraform -chdir=./devops/tf validate -no-color
      - name: Terraform Apply Changes 
        run: terraform -chdir=./devops/tf apply -auto-approve
      - name: Install Ansible
        run: |
          pip install ansible
      - name: Create PEM Key
        run: |
          cat << EOF > devops/ansible/private.pem
          ${{ secrets.ANSIBLE_PRIVATE_KEY }}
          EOF
      - name: Update key permissions
        run: |
          chmod 400 devops/ansible/private.pem
      - name: Add PEM Key Path to Ansible Config
        run: |
          cat << EOF > devops/ansible/ansible.cfg
          [defaults]
          ansible_python_interpreter='/usr/bin/python3'
          deprecation_warnings=False
          inventory=./inventory.ini
          remote_user="root"
          retries=2
          private_key_file = ./private.pem
          EOF
      - name: Run main playbook
        run: |
          cd devops/ansible
          ansible-playbook main.yaml
        